### ISSUE TITLE
Two suggestions for the future code

### ISSUE THREAD

**Issue by HenrikBengtsson** [schoulten/meedr#1]
Hi, congrats to you CRAN submission.  

Just two quick comments as author of **future** here.  Instead of:

```r
used_workers <- formals_parallel$workers
```

use

```r
used_workers <- future::nbrOfWorkers()
```

and instead of:

```r
msg <- utils::capture.output(future::plan())
flag <- grepl("sequential", msg)[1]
```

use

```r
flag <- inherits(future::plan(), "sequential")
```

**Comment by schoulten** [comment]
Thank you very much, @HenrikBengtsson, I love your suggestion! I will change that, it becomes much clearer.
